# -*- coding: utf-8 -*-
"""w1assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkvsP47YERF6QNF3K0B7ZN3NdTlS6NSb

# Assignment 1: Python & NumPy Fundamentals

> Done by Pranav Jahagirdar

## Section A: Theory Questions

### 1. Explain what Python is and mention any four features that make it suitable for data-related work.


Python is a high-level programming language that is easy to read and write. It is widely used in data science, machine learning, web development, and automation.

Four features that make Python suitable for data-related work:

1.   Simple Syntax – Python code is easy to understand and write.
2.   Large Library Support – Libraries like NumPy and Pandas help in data analysis.
3.   Platform Independent – It runs on Windows, Mac, and Linux.
4.   Open Source – It is free to use and has strong community support.

### 2. Mutable vs Immutable Data Types

Mutable Data Types:
*   Mutable data types are those whose values can be changed after they are created.
*   Example: list, dictionary.

Immutable Data Types:
*   Immutable data types cannot be changed after creation. If we try to modify them, a new object is created instead.
*   Example: int, float, string, tuple.

### 3. List vs Tuple

List:
*   Mutable
*   Uses square brackets []
*   Can be modified


Tuple:
*   Immutable
*   Uses round brackets ()
*   Cannot be modified

### 4. What are operators in Python? Explain any four types of operators with examples

Operators are symbols used to perform operations on variables and values.

Four types:

1.   Arithmetic Operators (+, -, *, /)
*   Used to perform mathematical operations.
*   Example: 5 + 2

2.   Comparison Operators (>, <, ==)
*   Used to compare two values and return True or False.
*   Example: 5 > 3

3.   Logical Operators (and, or, not)
*   Used to combine conditional statements.
*   Example: True and False

4.   Assignment Operators (=, +=)
*   Used to assign values to variables.
*   Example: x = 5

### 5. Explain the purpose of conditional statements. Write the general syntax of describe a real-life use case.

Conditional statements are used to make decisions in a program. They allow the program to execute different blocks of code based on certain conditions.


General syntax:
```
if condition:
    statement
elif condition:
    statement
else:
    statement
```

Real-life example: Checking if a student passed or failed based on marks.

### 6. What is a function? Explain the advantages of using functions in a program

A function is a block of code that performs a specific task and can be reused whenever needed. Functions help in organizing code into smaller, manageable parts.

Advantages:

*   Reduces repetition

*   Makes code organized

*   Improves readability

*   Easier debugging

### 7. Explain the difference between a for loop and a while loop. When would you prefer one over the other?

A **for loop** is used when the number of iterations is known in advance. It runs for a fixed number of times.

Example: Printing numbers from 1 to 10.

A **while loop** is used when the number of iterations is not known beforehand. It continues until a condition becomes false.

Example: Asking the user to enter a correct password until it matches.

Preference:

Use a **for loop** when working with sequences like lists or when the number of repetitions is fixed.

Use a **while loop** when repetition depends on a condition.

### 8. What is NumPy? Why is NumPy preferred over Python lists for numerical operations?

NumPy (Numerical Python) is a Python library used for numerical and mathematical operations. It provides support for arrays and matrix operations.

Why preferred over lists:

1.   Faster Execution – NumPy is implemented in C internally, making computations faster.

2.   Less Memory Usage – NumPy arrays use less memory compared to lists.

3.   Supports Vectorized Operations – Mathematical operations can be performed directly on entire arrays without loops.

4.   Better for Scientific Computations – Provides built-in mathematical functions.

### 9. Explain what slicing is. How does slicing work in Python lists and NumPy arrays?

Slicing is the process of extracting a portion of a sequence such as a list or array.

The general format of slicing is:
```
sequence[start : stop : step]
```
start → starting index

stop → ending index (not included)

step → interval between elements



In lists:
```
numbers = [1, 2, 3, 4, 5]
print(numbers[1:4])
```
In NumPy:
```
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[1:3])
```

### 10. What is the range() function? Explain its parameters with examples.

The range() function is used to generate a sequence of numbers. It is commonly used with loops.

Syntax:
```
range(start, stop, step)
```
*   start → starting number (default is 0)

*   stop → ending number (not included)

*   step → difference between numbers (default is 1)

Examples:

*   range(5) → generates 0, 1, 2, 3, 4

*   range(1, 6) → generates 1, 2, 3, 4, 5

*   range(1, 10, 2) → generates 1, 3, 5, 7, 9

### Write a short note on palindrome logic. What is the basic idea behind checking whether a number or string is a palindrome?

A palindrome is a number or string that reads the same forward and backward.

Examples:

*   121

*   madam

The basic idea behind checking for a palindrome is:

1.   Reverse the number or string.

2.   Compare the reversed version with the original.

3.   If both are equal, it is a palindrome. Otherwise, it is not.

In programming, this can be done either by reversing manually using loops or by comparing characters from the beginning and end moving toward the center.

## Section B: Coding Questions

### 1. Write a program that: Takes a number from the user. Checks whether the number is positive, negative, or zero. Displays an appropriate message
"""

num = int(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

"""### 2. Write a function that: Accepts a list of numbers Returns the sum and average of the list"""

def calculate_sum_and_average(numbers):
    total = 0

    for num in numbers:
        total += num

    average = total / len(numbers)

    return total, average


my_list = [10, 20, 30, 40, 50]

result = calculate_sum_and_average(my_list)

print("Sum of elements:", result[0])
print("Average of elements:", result[1])

"""### 3. Write a program using a for loop to print the first n even numbers, where n is taken as input from the user."""

n = int(input("Enter the value of n: "))

print("First", n, "even numbers are:")

for i in range(1, n + 1):
    print(2 * i)

"""### 4. Write a program to check whether a given string is a palindrome without using any built-in reverse function."""

text = input("Enter a string: ")

reversed_text = ""

for char in text:
    reversed_text = char + reversed_text

if text == reversed_text:
    print("The given string is a palindrome.")
else:
    print("The given string is not a palindrome.")

"""### 5. Create a NumPy array with at least 5 integer elements and: Print the array Print the maximum and minimum value Print the sum of all elements"""

import numpy as np

arr = np.array([5, 12, 7, 20, 9])

print("Array:", arr)

print("Maximum value:", np.max(arr))

print("Minimum value:", np.min(arr))

print("Sum of elements:", np.sum(arr))

"""###6. Write a program to print the following star pattern using loops:
```
* * * * *
* * * * *
* * * * *
* * * * *
* * * * *
```
"""

for i in range(5):
    for j in range(5):
        print("*", end=" ")
    print()

"""### 7. Given a list of numbers, write a program that: Uses slicing to create a new list containing alternate elements Prints both the original and sliced list"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

alternate_numbers = numbers[::2]

print("Original list:", numbers)
print("List with alternate elements:", alternate_numbers)

"""## Section C: Brainstorming and Research Questions

### 1. Why do programming languages provide both for and while loops instead of only one looping structure?

Programming languages provide both for and while loops because they are designed for different types of repetition.

A **for loop** is mainly used when the number of iterations is known beforehand. For example, if we want to print numbers from 1 to 10 or go through all elements in a list, a for loop is more convenient and readable.

A **while loop** is used when the number of iterations is not known in advance. It runs as long as a condition remains true. For example, asking the user to enter the correct password until it matches.

Having both loops makes programming more flexible and easier to understand. Using only one type of loop for all situations would make some tasks harder to write and less clear.

### 2. How does NumPy internally handle large numerical data faster than Python lists?

NumPy is faster than Python lists because of how it stores and processes data internally.

NumPy arrays store elements in a continuous block of memory, which allows faster access and efficient computation. In contrast, Python lists store references to objects, which requires more memory and extra processing time.

Also, NumPy is implemented using low-level languages like C. This allows mathematical operations to be performed directly on entire arrays without using Python loops. This feature is called vectorization. Because of this, NumPy can process large amounts of numerical data much faster than regular Python lists.

### 3. What problems might occur if functions are not used in large programs?

If functions are not used in large programs, several problems can occur:

*   The code becomes very long and difficult to manage.

*   There will be a lot of repeated code, which increases the chances of errors.

*   Debugging becomes harder because everything is written in one place.

*   Making changes becomes risky since modifying one part may affect other parts of the program.

Functions help divide a large program into smaller, manageable parts. This improves readability, maintainability, and organization of the code.

### 4. Can every problem be solved using only conditional statements? Why or why not?

No, every problem cannot be solved using only conditional statements.

Conditional statements are used for decision-making, but they do not handle repetition or data organization. Many problems require loops to repeat actions multiple times and functions to organize code into reusable blocks.

For example, printing numbers from 1 to 100 requires repetition, which cannot be done using only if statements. Therefore, programming requires a combination of conditionals, loops, functions, and data structures to solve problems effectively.

### 5. Why is logic building considered more important than syntax memorization in programming?

Logic building is more important because programming is mainly about solving problems. If a person understands the logic behind a problem, they can write the solution in any programming language.

Syntax can be learned easily by practice or by referring to documentation. However, without strong logical thinking, it becomes difficult to break down problems into smaller steps and design proper solutions.

In simple words, syntax tells us how to write code, but logic tells us what to write. That is why logic building is considered more important than memorizing syntax.
"""