# -*- coding: utf-8 -*-
"""w1assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twGkQ10WVMVJDIqzBn4kwMgIef07k4PF

# Assignment 2: Logic Building with Python & NumPy

> Done by Pranav Jahagirdar

## Section A: Theory Questions

### 1. Explain the flow of execution in a Python program that contains functions, loops, and conditional statements.

The flow of execution in a Python program starts from the first line and moves downward line by line. When the program encounters a function call, it temporarily jumps to the function definition, executes the statements inside it, and then returns back to the point where the function was called.

Loops (like for and while) repeat a block of code multiple times based on a condition. The program checks the loop condition before each iteration. If the condition is true, the loop body executes; otherwise, the loop stops.

Conditional statements (if, elif, else) control decision-making. The program checks the condition, and if it is true, it executes the corresponding block of code. If false, it checks the next condition or moves to the else block.

So overall, execution flows sequentially, but functions, loops, and conditionals change the order depending on logic and conditions.

### 2. Why are data types important in programming? Explain how choosing an incorrect data type can affect program output.

Data types define the kind of value a variable can store, such as integers, floats, strings, or booleans. They are important because operations behave differently depending on the data type.

For example, adding two integers performs arithmetic addition:
```
5 + 3 = 8
```

But adding two strings performs concatenation:
```
"5" + "3" = "53"
```

If we mistakenly store numbers as strings, calculations may give incorrect results. Also, using the wrong data type can cause errors or unexpected output. Therefore, choosing the correct data type ensures accurate calculations and proper program behavior.

### 3. Explain the role of operators in decision-making programs. Give suitable examples.

Operators are used to perform operations on variables and values. In decision-making programs, comparison and logical operators are especially important.

Comparison operators (>, <, ==, !=, >=, <=) compare values and return either True or False.

Example:
```
age = 18
if age >= 18:
    print("Eligible to vote")
```
Logical operators (and, or, not) combine multiple conditions.

Example:
```
marks = 75
attendance = 85

if marks >= 40 and attendance >= 75:
    print("Pass")
```
Here, operators help the program decide which block of code should be executed.

### 4. What happens internally when a for loop uses the range() function? Explain with an example.

When a for loop uses range(), Python generates a sequence of numbers. The loop variable takes one value at a time from this sequence.

For example:
```
for i in range(1, 5):
    print(i)
```
Here, range(1, 5) generates numbers starting from 1 up to 4 (5 is excluded). Internally, the loop:

1. Assigns 1 to i and executes the loop body.

2. Assigns 2 to i and executes the loop body.

3. Assigns 3 to i and executes the loop body.

4. Assigns 4 to i and executes the loop body.

5. Stops when the sequence ends.

So range() provides the values one by one until the limit is reached.

### 5. Explain how slicing helps in solving problems efficiently. Mention at least two practical use cases.

Slicing allows us to extract a portion of a sequence like a list or string using indexing. The syntax is:
```
sequence[start:end:step]
```
It helps solve problems efficiently because we can access required parts without writing extra loops.

Practical use cases:

1. Extracting a substring from a string
Example: Getting the first three characters of a word:
```
word = "Python"
print(word[:3])   # Output: Pyt
```
2. Reversing a list or string
```
numbers = [1, 2, 3, 4]
print(numbers[::-1])   # Output: [4, 3, 2, 1]
```
Slicing makes code shorter and more readable.

### 6. What is the importance of loop control conditions? What issues may arise if loop conditions are not defined properly?

Loop control conditions determine how long a loop runs. They are important because they prevent infinite execution and ensure the loop stops at the correct time.

If loop conditions are not defined properly:

* The loop may run forever (infinite loop).

* The loop may stop too early.

* The loop may not run at all.

* The program may consume too much memory or processing power.

Example of a problematic loop:
```
while x > 0:
    print(x)
```
If x is never updated inside the loop, it will run indefinitely. Therefore, loop conditions must be carefully defined and updated.

### 7. Explain how NumPy arrays differ from Python lists in terms of memory usage and performance.

NumPy arrays store elements of the same data type in contiguous memory locations. This makes them more memory-efficient compared to Python lists.

Python lists can store elements of different data types, but they require more memory because each element is stored as a separate object.

In terms of performance:

* NumPy arrays are faster for mathematical and numerical operations.

* They support vectorized operations, meaning operations can be performed on entire arrays at once without writing loops.

Example:
```
import numpy as np

a = np.array([1, 2, 3])
print(a * 2)   # Output: [2 4 6]
```
This is faster than manually multiplying each element using a loop.

### 8. Why is it recommended to break a large problem into smaller functions? Explain with a simple scenario.

Breaking a large problem into smaller functions makes the program easier to understand, test, and debug. Each function performs a specific task, which improves readability and modularity.

For example, consider a program that calculates a student’s final grade. Instead of writing everything in one block, we can create:

* A function to calculate total marks

* A function to calculate average

* A function to determine grade

This way:

* The code becomes organized.

* Errors can be identified easily.

* Functions can be reused in other programs.

Thus, dividing a problem into smaller functions improves clarity and maintainability.

## Section B: Coding Questions

### 1. Write a program that: Takes a number from the user. Uses a loop to calculate the sum of its digits. Displays the result.
"""

# Take input from user
num = int(input("Enter a number: "))

# Store original number (optional)
temp = num

# Make number positive (for negative inputs)
if num < 0:
    num = -num

sum_digits = 0

# Loop until number becomes 0
while num > 0:
    digit = num % 10        # Extract last digit
    sum_digits += digit     # Add digit to sum
    num = num // 10         # Remove last digit

print("Sum of digits:", sum_digits)

"""### 2. Write a function that: Accepts a list of integers. Returns a new list ontaining only even numbers."""

def get_even_numbers(numbers):
    even_list = []

    for num in numbers:
        if num % 2 == 0:
            even_list.append(num)

    return even_list


# Example usage
nums = [1, 2, 3, 4, 5, 6]
result = get_even_numbers(nums)
print("Even numbers:", result)

"""### 3. Write a program to generate the Fibonacci series up to n terms using a loop, where n is taken as user input."""

n = int(input("Enter number of terms: "))

a = 0
b = 1

if n <= 0:
    print("Enter a positive number")
elif n == 1:
    print(a)
else:
    print("Fibonacci series:")
    print(a)
    print(b)

    for i in range(2, n):
        c = a + b
        print(c)
        a = b
        b = c

"""### 4. Write a program that: Takes a list of numbers from the user. Uses slicing to reverse the list. Prints both the original and reversed list."""

# Take input as space-separated numbers
numbers = list(map(int, input("Enter numbers separated by space: ").split()))

# Reverse using slicing
reversed_list = numbers[::-1]

print("Original list:", numbers)
print("Reversed list:", reversed_list)

"""### 5. Create a NumPy array with at least 10 elements and write a program to: Extract the first half of the array using slicing. Calculate the sum of the extracted elements."""

import numpy as np

# Create NumPy array with at least 10 elements
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Extract first half using slicing
half = arr[:len(arr)//2]

# Calculate sum of extracted elements
total = np.sum(half)

print("Original array:", arr)
print("First half:", half)
print("Sum of first half:", total)

"""### 6. Write a program to check whether a given number is a palindrome using arithmetic operations (do not convert the number to a string)."""

num = int(input("Enter a number: "))

original = num
reverse = 0

# Make number positive if negative
if num < 0:
    num = -num

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num = num // 10

if original == reverse:
    print("The number is a palindrome")
else:
    print("The number is not a palindrome")

"""### 7. Write a program using nested loops to print the following pattern:
```
1 1 1 1
2 2 2 2
3 3 3 3
4 4 4 4
```
"""

for i in range(1, 5):        # Outer loop for rows
    for j in range(4):       # Inner loop for columns
        print(i, end=" ")
    print()                  # Move to next line

"""## Section C: Brainstorming and Research Questions

### 1. Why is writing logic on paper (or pseudocode) before coding considered a good practice?

Writing logic on paper or in pseudocode helps in organizing thoughts before starting to code. It allows us to clearly understand the steps required to solve the problem without worrying about syntax errors.

When we plan the logic first:

* We can identify mistakes early.

* The solution becomes more structured.

* Coding becomes faster and smoother.

Pseudocode acts as a blueprint for the program. It focuses on what needs to be done rather than how to write it in a specific language. This reduces confusion and improves problem-solving skills.

### 2. What limitations might you face if you rely only on loops and conditional statements for every problem?

Loops and conditional statements are important, but relying only on them can make programs:

* Very long and repetitive.

* Difficult to read and understand.

* Hard to debug.

For example, if we do not use functions, we may repeat the same code multiple times. Also, without using built-in methods or libraries (like NumPy), solving large data problems using only loops may be slow and inefficient.

Therefore, while loops and conditionals are basic building blocks, they are not always the most efficient solution for complex problems.

### 3. How does breaking a problem into functions improve debugging and maintenance?

When a program is divided into smaller functions, each function performs a specific task. This makes the program modular.

Benefits:

* If an error occurs, we can check the specific function instead of the entire program.

* It becomes easier to test each part separately.

* Updating or modifying one function does not affect the whole program.

For example, in a student result system, we can create separate functions for calculating total marks, average, and grade. If the grading rule changes, we only modify the grade function.

This improves both debugging and long-term maintenance.

### 4. In what real-world scenarios would slicing be more useful than looping through elements one by one?

Slicing is useful when we need a specific portion of data quickly.

Some real-world examples:

* Extracting the first few characters of a product code.

* Getting the last 5 transactions from a list of bank records.

* Splitting a dataset into two halves (training and testing).

* Reversing a sequence of numbers or characters.

Slicing makes the code shorter and more readable compared to manually using a loop to copy elements one by one.

### 5. Why is understanding errors and unexpected output an important part of learning programming?

Errors and unexpected outputs help us understand how the program actually works. They show us where our logic or assumptions are incorrect.

When we analyze errors:

* We learn how Python interprets our code.

* We improve our problem-solving ability.

* We become more careful while writing logic.

Debugging teaches patience and logical thinking. Instead of seeing errors as failures, they should be seen as opportunities to improve understanding and writing better programs.
"""