# -*- coding: utf-8 -*-
"""w1minorproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBxkCMsiL3319wT5Itvjm8SA4NxAZ0MG

# Minor Project – Student Marks Analyzer using Python and NumPy

> Done by Pranav Jahagirdar

### Problem Statement

This program takes marks of multiple students as input.
It stores the marks using NumPy arrays and performs basic analysis like total, average, highest, and lowest marks.
It also assigns a grade to the students based on their average marks.

## Logic explanation

*   First, the program asks how many students are there.

*   Then it collects marks for each student using a loop.

*   The marks are stored in a list.

*   The list is converted into a NumPy array.

*   NumPy functions are used to calculate:
    
    *   Total
    
    *   Average
    
    *   Maximum
    
    *   Minimum

*   A function is used to assign grades using conditional statements.

*   Finally, all results are displayed clearly.

## Complete code
"""

import numpy as np

def calculate_grade(average_mark):
    if average_mark > 85:
        return "A"
    elif average_mark >= 70:
        return "B"
    elif average_mark >= 50:
        return "C"
    else:
        return "Fail"

num_students = int(input("Enter number of students: "))

marks_list = []

for i in range(num_students):
    mark = float(input("Enter marks for student " + str(i+1) + ": "))
    marks_list.append(mark)

marks_array = np.array(marks_list)

total_marks = np.sum(marks_array)
average_marks = np.mean(marks_array)
highest_mark = np.max(marks_array)
lowest_mark = np.min(marks_array)
grade = calculate_grade(average_marks)

print("\n------- Marks Analysis -------")
print("Total Marks:", total_marks)
print("Average Marks:", average_marks)
print("Highest Mark:", highest_mark)
print("Lowest Mark:", lowest_mark)
print("Assigned Grade:", grade)

"""## Sample output

Enter number of students: 3

Enter marks for student 1: 90

Enter marks for student 2: 22

Enter marks for student 3: 70


----- Marks Analysis -----

Total Marks: 182.0

Average Marks: 60.666666666666664

Highest Mark: 90.0

Lowest Mark: 22.0

Assigned Grade: C
"""