-- ============================================
-- Minor Project – MySQL
-- Minor Project: Bike Store Sales & Inventory Analysis
-- Done by Pranav Jahagirdar
-- ============================================


 
-- Create the Database
 
CREATE DATABASE BikeStoreProject;
USE BikeStoreProject;


 
-- Task 1: Store Performance
-- Total revenue generated by each store
 
SELECT
    s.store_name AS Store_Name,
    SUM(oi.list_price * oi.quantity * (1 - oi.discount)) AS Total_Revenue
FROM stores AS s
JOIN orders AS o
    ON s.store_id = o.store_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY s.store_name
ORDER BY Total_Revenue DESC;


 
-- Task 2: Product Popularity
-- Top 5 most sold products by quantity
 
SELECT
    p.product_name AS Product_Name,
    SUM(oi.quantity) AS Total_Quantity_Sold
FROM products AS p
JOIN order_items AS oi
    ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY Total_Quantity_Sold DESC
LIMIT 5;


 
-- Task 3: Customer Location with Store Names
-- Customers who placed orders along with the store name
 
SELECT
    c.first_name AS First_Name,
    c.last_name AS Last_Name,
    c.city AS City,
    c.state AS State,
    s.store_name AS Store_Name
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
JOIN stores AS s
    ON o.store_id = s.store_id
ORDER BY First_Name;


 
-- Task 4: Brand Insights
-- Total number of products for each brand
 
SELECT
    b.brand_name AS Brand_Name,
    COUNT(p.product_id) AS Total_Products
FROM brands AS b
JOIN products AS p
    ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY Total_Products DESC;


 
-- Task 5: Low Stock Alert
-- Products with zero quantity available in stock

SELECT
    p.product_name AS Product_Name,
    s.store_name AS Store_Name,
    st.quantity AS Stock_Quantity
FROM stocks AS st
JOIN products AS p
    ON st.product_id = p.product_id
JOIN stores AS s
    ON st.store_id = s.store_id
WHERE st.quantity = 0
ORDER BY Product_Name;
