# -*- coding: utf-8 -*-
"""w6minorproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BonxFRYjJe9aD3B5IcpduvXE8pmWWx9W

# MINOR PROJECT: Real-World Statistics Project

> Done by Pranav Jahagirdar

### Dataset

https://github.com/NelakurthiSudheer/Mall-Customers-Segmentation/blob/main/Dataset/Mall_Customers.csv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""## SECTION 1: Data Understanding

### Tasks:
"""

# load dataset
df = pd.read_csv('Mall_Customers.csv')

# dataset shape
print("\nDataset shape:", df.shape)

# column names
print("\nColumns:", df.columns)

# Check missing values
df.isnull().sum()

# Check data types
df.dtypes

"""### Questions:

**1. What type of dataset is this?**

This is a customer segmentation dataset. It contains structured data about mall customers, including their age, income, gender, and spending behavior. It is mainly used for analyzing customer patterns and understanding how different customers behave.

**2. Which features are numerical/categorical?**

Numerical features: CustomerID, Age, Annual Income (k$), Spending Score (1-100)

Categorical feature: Gender.

## SECTION 2: Descriptive Analysis

### Tasks:
"""

# take random sample
sample = df.sample(n=100, random_state=42)

features = ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']

for col in features:
    print(f"\n--- {col} ---")
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Standard Deviation:", df[col].std())

"""### Questions:

**1. Which feature shows highest variability?**

Annual Income shows the highest variability because it has the largest standard deviation compared to Age and Spending Score.

**2. Are customers similar or diverse?**

Customers are quite diverse, especially in terms of income and spending score. Age is relatively more consistent, but income and spending vary significantly across customers.

## SECTION 3: Visualization

### Tasks:
"""

# plot histograms
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
sns.histplot(df['Age'], bins=20, kde=True)
plt.title('Age Distribution')

plt.subplot(1,3,2)
sns.histplot(df['Annual Income (k$)'], bins=20, kde=True)
plt.title('Income Distribution')

plt.subplot(1,3,3)
sns.histplot(df['Spending Score (1-100)'], bins=20, kde=True)
plt.title('Spending Score Distribution')

plt.show()

# plot boxplots
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
sns.boxplot(y=df['Age'])
plt.title('Age Boxplot')

plt.subplot(1,3,2)
sns.boxplot(y=df['Annual Income (k$)'])
plt.title('Income Boxplot')

plt.subplot(1,3,3)
sns.boxplot(y=df['Spending Score (1-100)'])
plt.title('Spending Score Boxplot')

plt.show()

"""### Questions:

**1. Is data skewed?**
The data is slightly skewed in some features. Income and spending score show mild skewness, while age appears more normally distributed.

**2. Are there extreme customers?**
Yes, there are a few extreme values visible in the boxplots, especially in income and spending score. These indicate some customers who earn or spend significantly more than others.

## SECTION 4: Group-Based Analysis

### Tasks:
"""

# group by gender and calculate averages

group_analysis = df.groupby('Gender')[['Spending Score (1-100)', 'Annual Income (k$)']].mean()

group_analysis

# bar plots for better comparison

group_analysis.plot(kind='bar', figsize=(8,5))
plt.title('Average Spending Score and Income by Gender')
plt.ylabel('Average Value')
plt.xticks(rotation=0)
plt.show()

"""### Questions:

**1. Which group spends more?**
Female customers tend to have a slightly higher average spending score compared to male customers.

**2. Is there a visible difference?**
Yes, there is a noticeable difference in spending behavior. While the income levels are somewhat similar, females generally have higher spending scores, indicating they spend more on average.

## SECTION 5: Correlation Analysis

### Tasks:
"""

# correlation values

income_spending_corr = df['Annual Income (k$)'].corr(df['Spending Score (1-100)'])
age_spending_corr = df['Age'].corr(df['Spending Score (1-100)'])

print("Correlation (Income vs Spending Score):", income_spending_corr)
print("Correlation (Age vs Spending Score):", age_spending_corr)

# correlation heatmap

plt.figure(figsize=(6,4))
sns.heatmap(df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].corr(),
            annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""### Questions:

**1. Do richer customers spend more?**
No, there is no strong relationship between income and spending score. The correlation is weak, which means higher income does not necessarily lead to higher spending.

**2. Does age affect spending?**
Yes, age shows a negative correlation with spending score. This suggests that younger customers tend to spend more, while older customers generally spend less.

## SECTION 6: Inferential Statistics (CORE)

### Problem Statement:
 Do male and female customers spend differently?

**Step 1: Hypothesis**

*   Null Hypothesis (H₀): There is no difference in spending between male and female customers.
*   Alternative Hypothesis (H₁): There is a difference in spending between male and female customers.

**Step 2: Perform T-Test**
"""

from scipy import stats

# Split data into two groups
male = df[df['Gender'] == 'Male']['Spending Score (1-100)']
female = df[df['Gender'] == 'Female']['Spending Score (1-100)']

# Perform independent t-test
t_stat, p_value = stats.ttest_ind(male, female)

print("T-statistic:", t_stat)
print("P-value:", p_value)

"""**Step 3: Decision Rule**"""

# Decision based on p-value

if p_value < 0.05:
    print("Reject H0 → There is a significant difference in spending.")
else:
    print("Fail to reject H0 → No significant difference in spending.")

"""**Interpretation:**

The t-test compares the average spending scores of male and female customers.
Based on the p-value, we decide whether the difference is statistically meaningful or just due to random variation.

### Questions:

**1. What does p-value tell you?**
The p-value represents the probability that the observed difference in spending occurred by chance. A smaller value indicates stronger evidence against the null hypothesis.

**2. Is the difference statistically significant?**
Yes, since the p-value is less than 0.05, we reject the null hypothesis. This means there is a statistically significant difference in spending between male and female customers.

## SECTION 7: Confidence Interval

### Tasks:
"""

import numpy as np
from scipy import stats

# Spending Score data
spending = df['Spending Score (1-100)']

# Sample statistics
mean = np.mean(spending)
std_err = stats.sem(spending)  # standard error

# 95% Confidence Interval
ci = stats.t.interval(0.95, len(spending)-1, loc=mean, scale=std_err)

print("Mean Spending Score:", mean)
print("95% Confidence Interval:", ci)

"""**Interpretation:**

The confidence interval gives a range in which the true average spending score of all customers is likely to fall.
It provides a better understanding than just a single mean value.

### Questions:

**1. What range do customers fall into?**
The average spending score lies within the calculated 95% confidence interval. This means most customers’ true average spending is expected to fall within this range.

**2. How confident are we?**
We are 95% confident that the true mean spending score of all customers lies within this interval. This does not mean every value falls in the range, but that the estimate is reliable.

## SECTION 8: Business Insights

### Questions:

**1. Which customers should the business target?**
The business should target customers with high spending scores, especially those with moderate to high income. These customers are more likely to make frequent purchases and generate higher revenue.

**2. Does income affect spending?**
Income does not have a strong impact on spending. The correlation is weak, which means higher income does not always lead to higher spending.

**3. Should marketing differ by gender?**
Yes, marketing can be slightly tailored by gender since females tend to have higher spending scores. However, the difference is not extremely large, so strategies should not rely only on gender.

**4. What strategy would you suggest?**
The business should focus on customer segmentation and target high-spending groups with personalized offers. Promotions, loyalty programs, and targeted advertising can help increase engagement and sales.
"""