# -*- coding: utf-8 -*-
"""w7minorproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvGbpIqEPvx890nyT8LCTFC5M4CwVrlT

# MINOR PROJECT – SUPERVISED LEARNING

> Done by Pranav Jahagirdar

## PART A – REGRESSION

**Medical Cost Prediction**

**Objective:** Build a Linear Regression model to predict medical insurance charges.

### SECTION 1 – Data Understanding
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#### 1. Load the dataset and display:
- Shape
- Column names
- Data types
- First 5 rows
"""

# Load dataset
df = pd.read_csv("insurance.csv")

# Basic info
print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nData Types:\n", df.dtypes)

# First 5 rows
df.head()

"""#### 2. Check:
- Missing values
- Duplicate rows
"""

# Missing values
print(df.isnull().sum())

# Duplicates
print("Duplicate rows:", df.duplicated().sum())

"""#### 3. Perform EDA:
- Distribution of charges
- Scatter plot: age vs charges
- Boxplot: smoker vs charges
- Correlation heatmap
"""

# Distribution of charges
sns.histplot(df['charges'], kde=True)
plt.title("Distribution of Charges")
plt.show()

# Scatter plot: age vs charges
sns.scatterplot(x='age', y='charges', data=df)
plt.show()

# Boxplot: smoker vs charges
sns.boxplot(x='smoker', y='charges', data=df)
plt.show()

# Correlation heatmap
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

"""#### 4. Write 3 observations from EDA.

**Observations**

1. Charges are highly right-skewed (few people pay very high costs).
2. Smokers have significantly higher medical charges.
3. Age shows a positive relationship with charges.

### SECTION 2 – Data Preprocessing

#### 5. Encode categorical variables properly.
"""

# Encoding categorical variables
df['sex'] = df['sex'].map({'male':1, 'female':0})
df['smoker'] = df['smoker'].map({'yes':1, 'no':0})

df = pd.get_dummies(df, columns=['region'], drop_first=True)

"""#### 6. Separate features (X) and target (y)."""

# Features and target
X = df.drop('charges', axis=1)
y = df['charges']

"""#### 7. Perform train-test split (80-20)."""

# Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""#### 8. Apply feature scaling (if required)."""

# Feature scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""#### 9. Explain why scaling is / isn’t required.

**Explanation**

Scaling is applied because Linear Regression performs better when features
are on the same scale, especially when coefficients are interpreted.

### SECTION 3 – Model Building

#### 10. Train a Linear Regression model.
"""

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

"""#### 11. Display:
- Intercept
- Coefficients
"""

# Intercept and coefficients
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

"""#### 12. Write the regression equation.

**Regression Equation**

charges = intercept + (coef1 * feature1) + (coef2 * feature2) + ...

### SECTION 4 – Model Evaluation

#### 13. Predict on test data.
"""

# Predictions
y_pred = model.predict(X_test)

"""#### 14. Calculate:
- MAE
- MSE
- RMSE
- R2 Score
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

"""#### 15. Plot:
- Actual vs Predicted
- Residual plot
"""

# Actual vs Predicted
plt.scatter(y_test, y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

# Residual plot
sns.residplot(x=y_pred, y=y_test - y_pred)
plt.title("Residual Plot")
plt.show()

"""#### 16. Interpret R2 score.

**Interpretation**

R2 score shows how well the model explains variance.
Higher R2 (~0.7–0.8) indicates a reasonably good model.

### SECTION 5 – Business Insights

17. Which variable impacts charges the most?

A. Smoking is the most impactful factor affecting medical charges.

18. How much more do smokers pay?

A. Smokers pay significantly higher charges compared to non-smokers.

19. Is BMI statistically impactful?

A. BMI has some impact, but not as strong as smoking.

20. Can this model be used in production? Why or why not?

A. The model performs reasonably well but may not generalize perfectly in real-world scenarios.

## PART B – CLASSIFICATION

**Movie Rating Prediction**

**Objective:** Build a classification model to predict whether a movie is a Hit or Flop.

Define:
- Hit = rating >= 7
- Flop = rating < 7

### SECTION 1 – Data Understanding

#### 21. Load dataset and display:
- Shape
- Columns
- Data types
"""

# Load dataset
movies = pd.read_csv("tmdb_5000_movies.csv")

print("Shape:", movies.shape)
print("\nColumns:", movies.columns)
print("\nData Types:\n", movies.dtypes)

"""#### 22. Check missing values."""

# Missing values
print(movies.isnull().sum())

movies = movies.dropna()

"""#### 23. Create binary target column: Hit"""

# Create target variable
movies['Hit'] = movies['vote_average'].apply(lambda x: 1 if x >= 7 else 0)

"""#### 24. Show class distribution."""

# Class distribution
print(movies['Hit'].value_counts())

sns.countplot(x='Hit', data=movies)
plt.show()

"""#### 25. Plot rating distribution.
- Write 3 observations.
"""

# Rating distribution
sns.histplot(movies['vote_average'], kde=True)
plt.xlabel("Rating")
plt.title("Distribution of Movie Ratings")
plt.show()

"""Observations

1. Most movies have ratings between 5 and 7.
2. Only a smaller portion qualify as 'Hit' (>=7).
3. Dataset is slightly imbalanced toward Flop movies.

### SECTION 2 – Data Preprocessing

#### 26. Drop irrelevant columns.
"""

# Drop irrelevant columns (example)
movies = movies.drop(['title'], axis=1, errors='ignore')

"""#### 27. Encode categorical variables."""

# Encoding
movies = pd.get_dummies(movies, drop_first=True)

"""#### 28. Separate X and y."""

# Features & target
X = movies.drop(['Hit', 'vote_average'], axis=1)
y = movies['Hit']

"""#### 29. Train-test split (80-20)."""

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""#### 30. Scale if required."""

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""### SECTION 3 – Model Building

#### 31. Train Logistic Regression model.
"""

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train)

"""#### 32. Display model coefficients."""

print("Coefficients:", clf.coef_)

"""#### 33. Explain what coefficients mean.

**Explanation**

Coefficients show how each feature affects probability of being a Hit.
Positive → increases chance of success
Negative → decreases chance

### SECTION 4 – Evaluation

#### 34. Predict test data.
"""

y_pred = clf.predict(X_test)

"""#### 35. Calculate:
- Accuracy
- Precision
- Recall
- F1 Score
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

"""#### 36. Plot Confusion Matrix."""

# Confusion matrix
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')
plt.show()

"""#### 37. Explain:
- Why accuracy alone is not enough?
- Which metric matters more here?

**Explanation**

Accuracy alone is not enough because the dataset is slightly imbalanced.
A model predicting all movies as 'Flop' could still get decent accuracy.

F1-score is more important because it balances Precision and Recall.

### SECTION 5 – Business Interpretation

38. What factors influence movie success?

A. Higher budget and popularity tend to increase chances of success.

39. Is the dataset balanced?

A. Dataset is slightly imbalanced but usable.

40. Would you trust this model for production? Why?

A. Model can be improved using feature engineering and advanced algorithms. Not fully reliable for production without tuning and validation.
"""